#!/usr/bin/env bash
# transfer a file to a server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path=$1
	ip=$2
	user=$3
	ssh_key=$4
	scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" scp://"$user"@"$ip"/~
fi
