#!/usr/bin/env bash
# display the contents of the file /etc/passwd
# displays only:
#	username
#	user id
#	home directory of the user

file=/etc/passwd
while read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < "$file"
