#!/usr/bin/env bash
# display the content of the file `/etc/passwd`
# using a while loop + IFS

while IFS=":" read -r login_name password uid gid username homedir shell
do
	echo "The user $login_name is part of the $gid gang,"\
		"lives in $homedir and rides $shell. $uid's place is"\
		"protected by the passcode $password, more info"\
		"about the user here: $username"
done < "/etc/passwd"
