#!/usr/bin/env bash
# loop from 1 to 10 and:
#  display "bad luck" for the 4th iteration
#  display "good luck" for the 8th iteration
#  display "Best School" for the other iterations

i=1
while ((i <= 10))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
