#!/usr/bin/env bash
# display the time for 12 hours and 59 minutes

hour=0
while ((hour <= 12))
do
	echo "Hour: $hour"
	((hour++))
	minute=1
	while ((minute <= 59))
	do
		echo "$minute"
		((minute++))
	done
done
